apiVersion: v1
kind: Pod 
metadata: 
	name: nginx 
	labels: 
		app: nginx 
spec: 
	containers: 
		- name: nginx—container 
			image: nginx 
			ports: 
			-containerPort: 80 
		-name : sidecar #installing curl command for this container
		Image: curlimage/curl
		command:["/bin/sh"]
		args: ["-c", "echo Hello from the sideca container; sleep 300"]
