# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weatherUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


#importing the libraries needed
import subprocess
import requests
import json


##-----------------------------##



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.weather_output = QtWidgets.QTabWidget(self.centralwidget)
        self.weather_output.setGeometry(QtCore.QRect(210, 40, 521, 281))
        self.weather_output.setObjectName("weather_output")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.weatherInfo_output = QtWidgets.QTextBrowser(self.tab)
        self.weatherInfo_output.setGeometry(QtCore.QRect(0, 0, 521, 261))
        self.weatherInfo_output.setObjectName("weatherInfo_output")
        self.weather_output.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.weather_output.addTab(self.tab_2, "")
        self.log = QtWidgets.QTextBrowser(self.centralwidget)
        self.log.setGeometry(QtCore.QRect(30, 370, 741, 171))
        self.log.setObjectName("log")
        self.current_location = QtWidgets.QPushButton(self.centralwidget)
        self.current_location.setGeometry(QtCore.QRect(20, 200, 161, 41))
        self.current_location.setObjectName("current_location")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.weather_output.setCurrentIndex(0)
        self.current_location.clicked.connect(self.get_data) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def get_data(self):
        self.log.append('getting the data from weather API.')
        def get_external_ip():
            response = requests.get('http://api.ipify.org')
            return response.text

        external_ip = get_external_ip()
        print("Your external IP is:", external_ip)


        def get_long_lat(external_ip):
            self.log.append("getting the current IP")
            app.processEvents()
            url = "https://get.geojs.io/v1/ip/geo/%s.json"%external_ip
            response = requests.get(url)
            #print (response.text)
            jj = response.json()
            country = jj["country"]
            city = jj["city"]
            self.log.append("getting the geographic location") 
            print (country, city)
            print (response.text)
            return response.json(), country, city

        jj,country,city = get_long_lat(external_ip)
        long = jj["longitude"]
        lat = jj["latitude"] 
        result = "Your country is "+country+" and your city is "+city+"."
        #print(result)
        self.log.append(result)
        #self.weatherInfo_output.append(result)
        self.log.append("Done.")
        app.processEvents()
        def run_another_file_and_capture_output():
            # Running run_this.py and capturing its output
            result = subprocess.getoutput(["python", "WeatherAPI.py"])
            app.processEvents()
            return result.strip()

        app.processEvents()
        output = run_another_file_and_capture_output()
        #print (output)
        self.weatherInfo_output.append(output)
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.weather_output.setTabText(self.weather_output.indexOf(self.tab), _translate("MainWindow", "Weather Info"))
        self.weather_output.setTabText(self.weather_output.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.current_location.setText(_translate("MainWindow", "Use my current location"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
