apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
spec:
  selector:
    app: aggregator-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: LoadBalancer
